buyorder/urls.py
from django.urls import path
from . import views

app_name = 'buyorder'

urlpatterns = [

    path('create_buyorder', views.create_buyorder, name='create_buyorder'),
    path('buyorder_list', views.buyorder_list, name='buyorder_list'),
    path('buyorder_list_by_date', views.buyorder_list_by_date, name='buyorder_list_by_date'),
    path('buyorder_confirmation/<str:pk>', views.buyorder_confirmation, name='buyorder_confirmation'),
    path('buyorder_pdf/<str:pk>', views.buyorder_pdf, name='buyorder_pdf'),
    path('buyorder_details/<str:pk>', views.buyorder_details, name='buyorder_details'),
    path('buyorderorder_list_by_supplier/<str:pk>', views.buyorderorder_list_by_supplier, name='buyorderorder_list_by_supplier'),
    path('buyorder_delete/<str:pk>', views.buyorder_delete, name='buyorder_delete'),
    path('update_order/<str:pk>', views.update_order, name='update_order'),
    path('confirm_all', views.confirm_all, name='confirm_all'),

    path('confirm_order_item_delete/<str:orderpk>/<str:itempk>', views.confirm_order_item_delete,
         name='confirm_order_item_delete'),


    # fixing dates
    path('fixing_dates', views.add_date_to_order, name='fixing_dates')
]

mygarage/urls.py
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

from mygarage import settings

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    # the main ressource
    path('', include('accounts.urls', namespace='accounts')),
    # offline connection
    # path('', include('pwa.urls')),
    path('customer/', include('customer.urls', namespace='customer')),
    path('supplier/', include('supplier.urls', namespace='supplier')),
    path('payments/', include('payments.urls', namespace='payments')),
    path('family/', include('family.urls', namespace='family')),
    path('category/', include('category.urls', namespace='category')),
    path('stock/', include('stock.urls', namespace='stock')),
    path('product/', include('product.urls', namespace='product')),
    path('buyorder/', include('buyorder.urls', namespace='buyorder')),
    path('sellorder/', include('sellorder.urls', namespace='sellorder')),
    path('billing/', include('billing.urls', namespace='billing')),
    path('vehicule/', include('vehicule.urls', namespace='vehicule')),
    path('rdv/', include('rdv.urls', namespace='rdv')),
    path('caisse/', include('caisse.urls', namespace='caisse')),
    path('bank/', include('bank.urls', namespace='bank')),
    path('services/', include('services.urls', namespace='services')),
    path('employee/', include('employee.urls', namespace='employee')),
    # path('discount/', include('discount.urls', namespace='discount')),

    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payments/urls.py
from django.urls import path
from . import views

app_name = 'payments'

urlpatterns = [
    # Customer
    path('create_customer_payment/<str:pk>', views.create_customer_payment, name='create_customer_payment'),
    path('create_customer_cheque/<str:pk>', views.create_customer_cheque, name='create_customer_cheque'),
    path('create_customer_verment/<str:pk>', views.create_customer_verment, name='create_customer_verment'),
    path('delete_customer_payment/<str:pk>', views.delete_customer_payment, name='delete_customer_payment'),
    path('customer_payment_list', views.customer_payment_list, name='customer_payment_list'),

    # Supplier
    path('create_supplier_payment/<str:pk>', views.create_supplier_payment, name='create_supplier_payment'),
    path('create_supplier_payment_by_supplier/<str:pk>', views.create_supplier_payment_by_supplier, name='create_supplier_payment_by_supplier'),
    path('create_supplier_cheque/<str:pk>', views.create_supplier_cheque, name='create_supplier_cheque'),
    path('supplier_payment_list', views.supplier_payment_list, name='supplier_payment_list'),
    path('delete_supplier_payment/<str:pk>', views.delete_supplier_payment, name='delete_supplier_payment'),
    path('delete_supplier_by_supplier_payment/<str:pk>', views.delete_supplier_by_supplier_payment,
         name='delete_supplier_by_supplier_payment'),

    # Service
    path('create_service_payment/<str:pk>', views.create_service_payment, name='create_service_payment'),
    path('service_payment_list', views.service_payment_list, name='service_payment_list'),
    path('delete_service_payment/<str:pk>', views.delete_service_payment, name='delete_service_payment'),

]

product/urls.py
from django.urls import path
from . import views

app_name = 'product'

urlpatterns = [
    path('all_product_list/', views.all_product_list, name='all_product_list'),
    # path('product_list/<str:pk>', views.product_list, name='product_list'),
    path('add_product', views.add_product, name='add_product'),
    path('delete_duplicated', views.delete_duplicated, name='delete_duplicated'),
    path('add_product_buyorder', views.add_product_buyorder, name='add_product_buyorder'),
    path('update_product/<str:pk>', views.update_product, name='update_product'),
    path('detail_product/<str:pk>', views.detail_product, name='detail_product'),
    path('delete_product/<str:pk>', views.delete_product, name='delete_product'),

]

rdv/urls.py
from django.urls import path
from . import views

app_name = 'rdv'

urlpatterns = [

    path('create_rdv_customer', views.create_rdv_customer, name='create_rdv_customer'),
    path('rdv_vehicle_list/<str:pk>', views.rdv_vehicle_list, name='rdv_vehicle_list'),
    path('rdv_list', views.rdv_list, name='rdv_list'),
    path('create_rdv/<str:pk>', views.create_rdv, name='create_rdv'),
    path('rdv_pdf/<str:pk>', views.rdv_pdf, name='rdv_pdf'),
    path('rdv_details/<str:pk>', views.rdv_details, name='rdv_details'),
    path('delete_rdv/<str:pk>', views.delete_rdv, name='delete_rdv'),

    # Panne
    path('create_panne', views.create_panne, name='create_panne'),
    path('panne_list', views.panne_list, name='panne_list'),
    path('update_panne/<str:pk>', views.update_panne, name='update_panne'),
    path('update_order_panne_list/<str:pk>', views.update_order_panne_list, name='update_order_panne_list'),
    path('confirm_order_panne_list/<str:pk>', views.confirm_order_panne_list, name='confirm_order_panne_list'),
    path('order_panne_list/<str:pk>', views.order_panne_list, name='order_panne_list'),
    path('delete_panne/<str:pk>', views.delete_panne, name='delete_panne'),

]

stock/urls.py
from django.urls import path
from . import views

app_name = 'stock'

urlpatterns = [

    path('add_stock', views.add_stock, name='add_stock'),
    path('stock_list', views.stock_list, name='stock_list'),
    path('all_stock_list', views.all_stock_list, name='all_stock_list'),
    path('update_stock/<str:pk>', views.update_stock, name='update_stock'),
    path('delete_stock/<str:pk>', views.delete_stock, name='delete_stock'),
    path('reset_stock/<str:pk>', views.reset_stock, name='reset_stock'),
    path('calculate_general_stock', views.calculate_general_stock, name='calculate_general_stock'),
    path('calculate_one_stock/<str:pk>', views.calculate_one_stock, name='calculate_one_stock'),

    path('add_stockproduct', views.add_stockproduct, name='add_stockproduct'),
    path('stockproduct_list/<str:pk>', views.stockproduct_list, name='stockproduct_list'),
    path('stock_product_details/<str:pk>', views.stock_product_details, name='stock_product_details'),
    path('all_stockproduct_list', views.all_stockproduct_list, name='all_stockproduct_list'),
    path('order_stockproduct_list/<str:pk>', views.order_stockproduct_list, name='order_stockproduct_list'),

    path('performa_order_stockproduct_list/<str:pk>', views.performa_order_stockproduct_list,
         name='performa_order_stockproduct_list'),

    path('modal_order_stockproduct_list/<str:pk>', views.modal_order_stockproduct_list,
         name='modal_order_stockproduct_list'),
    path('modal_buyorder_stockproduct_list/<str:pk>', views.modal_buyorder_stockproduct_list,
         name='modal_buyorder_stockproduct_list'),
    path('modal_update_order_stockproduct_list/<str:pk>', views.modal_update_order_stockproduct_list,
         name='modal_update_order_stockproduct_list'),

    path('update_stockproduct/<str:pk>', views.update_stockproduct, name='update_stockproduct'),
    path('delete_stockproduct/<str:pk>', views.delete_stockproduct, name='delete_stockproduct'),
    path('stockproductcategory_list/<str:pk>', views.stockproductcategory_list, name='stockproductcategory_list'),
    path('stockproduct_detail/<str:id>', views.stockproduct_detail, name='stockproduct_detail'),

    path('order_vehicle/<str:pk>', views.order_vehicle, name='order_vehicle'),
    path('performa_order_vehicle/<str:pk>', views.performa_order_vehicle, name='performa_order_vehicle'),
    path('stockproduct_stockalert', views.stockproduct_quantityalert, name='stockproduct_stockalert'),
    path('delete_duplicated_stockproduct', views.delete_duplicated_stockproduct, name='delete_duplicated_stockproduct'),
    path('putit_in_stock', views.putit_in_stock, name='putit_in_stock'),

]

buyorder/models.py
from decimal import Decimal

from django.db import models
from product.models import Product
from stock.models import Stock
from supplier.models import Supplier


# Create your models here.

class BuyOrder(models.Model):
    user = models.IntegerField(default=0)
    supplier = models.ForeignKey(Supplier, on_delete=models.DO_NOTHING, related_name="orders")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)
    order_tva = models.PositiveIntegerField(default=0)
    debt = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True, default=0)
    confirmed = models.BooleanField(default=False)
    order_date = models.DateField(null=True, blank=True)
    total_price = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True, default=0)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return f'Order {self.id}'

    def get_total_cost(self):
        return round(sum(item.get_cost() for item in self.items.all()), 2)

    def get_tva(self):
        return round(self.get_total_cost() * Decimal(self.order_tva/100), 2)

    def get_ttc(self):
        return round(self.get_total_cost() + self.get_tva(), 2)


class BuyOrderItem(models.Model):
    order = models.ForeignKey(BuyOrder,
                              related_name='items',
                              on_delete=models.CASCADE)
    product = models.ForeignKey(Product,
                                related_name='buyorder_item',
                                on_delete=models.DO_NOTHING, null=True, blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    stock = models.ForeignKey(Stock, related_name='item_stocks', on_delete=models.DO_NOTHING, null=True, blank=True)

    def __str__(self):
        return str(self.id)

    def get_cost(self):
        return round(self.price * self.quantity, 2)

buyorder/forms.py
from django.forms import ModelForm, modelformset_factory
from buyorder.models import BuyOrder, BuyOrderItem
from product.models import Product
from django import forms


class BuyOrderForm(ModelForm):
    class Meta:
        model = BuyOrder

        fields = ['supplier', ]


# create a form and put it in a formset so you can control some fields property and init the form
class BuyOrderItemForm(forms.ModelForm):
    class Meta:
        model = BuyOrderItem
        widgets = {
            'product': forms.Select(attrs={'class': 'chosen form-control'}),
            # forms.TextInput(attrs={'class': 'form-control product_name'}),
            'quantity': forms.NumberInput(attrs={'class': 'form-control'}),
            'price': forms.NumberInput(attrs={'class': 'form-control'}),

        }

        fields = ['product', 'quantity', 'price']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # if the user hit submit but didn't choose a
        # color & type we fill it directly from product field
        if 'product' in self.data:
            try:
                requestproduct = int(self.data.get('product'))
                splitedproduct = requestproduct.split()
                product = Product.objects.get(id=splitedproduct[0])
                self.fields['price'].queryset = product.buyprice
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        # elif self.instance.pk:
        #     self.fields['city'].queryset = self.instance.country.city_set.order_by('name')


BuyOrderItemFormset = modelformset_factory(
    BuyOrderItem,
    form=BuyOrderItemForm,
    extra=1,
)

buyorder/templates/buyorder/buyorder_delete.html
{% extends 'home.html' %}
{% load static %}
{% load i18n %}
{% block content %}
<br>
<br>
<div class="container">
    <div class="row">
    <div class="col-md-3">
    </div>
    <div class="col-md-6">
        <div class="card card-body">
            <P>{% trans "ARE YOU SURE YOU WANT TO DELETE" %} {{order}}</P>
            <form action="{% url 'buyorder:buyorder_delete' order.id %}" method="post">

                {% csrf_token %}
                <a class="btn btn-warning" href="{% url 'buyorder:buyorder_list' %}">{% trans "Cancel" %}</a>
                <input class="btn btn-danger" type="submit" name="Confirm">
            </form>
        </div>
    </div>
    <div class="col-md-3">
    </div>
</div>
</div>

{% endblock %}

buyorder/templates/buyorder/buyorder_details.html
{% extends 'home.html' %}
{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block content %}
<br>
<div class="row">
    <div class="col-md">
        <div class="card card-body">
            <h5>{% trans "Order Details" %}</h5>
            {% if order.debt > 0 %}
                        <a class="btn btn-primary " href="{% url 'payments:create_supplier_payment' order.id %}">PayDebt</a>
            {% endif %}
            <br>
            <a class="btn btn-warning " href="{% url 'buyorder:buyorder_pdf' order.id %}">{% trans "Print" %} </a>

        </div>
        <div class="card card-body">
            <div class="row">
                <div class="col-md-2">
                    <h6>{% trans "Order ID" %}: </h6>
                    <td>{{order.id}}</td>
                </div>
                <div class="col-md-2">
                    <h6>{% trans "Supplier" %}: </h6>
                    <td>{{order.supplier}}</td>
                </div>
                <div class="col-md-2">
                    <h6>{% trans "Phone" %}: </h6>
                    <td>{{order.supplier.phone}}</td>
                </div>
                <div class="col-md-2">
                    <h6>{% trans "Paid" %}: </h6>
                    <td>{{order.paid}}</td>
                </div>
                <div class="col-md-2">
                    <h6>{% trans "Total Price" %}: </h6>
                    <td>{{order.get_ttc}} {% trans "DZD" %}</td>
                </div>
                <div class="col-md-2">
                    <h6>Debt: </h6>
                    <td>{{order.debt}} {% trans "DZD" %}</td>
                </div>
            </div>
            <table id="table_id" class="table display text-center">
                <thead class="thead-light">
                <tr>
                    <th>{% trans "Product Brand" %}</th>
                    <th>{% trans "Product Name" %}</th>
                    <th>{% trans "Price" %}</th>
                    <th>{% trans "Quantity" %}</th>
                    <th>{% trans "Total Price" %}</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                {% for item in order.items.all %}
                <tr>
                    <td class="table-light">{{ item.product.brand }}</td>
                    <td class="table-light">{{ item.product.name }}</td>
                    <td class="table-light ">DZD{{ item.price }}</td>
                    <td class="table-light ">{{ item.quantity }}</td>
                    <td class="table-light">DZD{{ item.get_cost }}</td>
                    <td class="table-light"></td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
            <br>

            <h2> {% trans "Payments" %} </h2>
            <hr>
            <table id="table_payments" class="table display text-center">
                <thead class="thead-light">
                <tr>
                    <th>{% trans "Supplier" %}</th>
                    <th>{% trans "Pay Status" %}</th>
                    <th>{% trans "Amount" %}</th>
                    <th>{% trans "Created" %}</th>
                    <th>{% trans "Payed" %}</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                {% for payment in buyorder_payments %}
                <tr>
                    <td class="table-light">
                        {{payment.supplier}}
                    </td>
                    <td class="table-light">
                        {{payment.pay_status}}
                    </td>
                    <td class="table-light">
                        {{payment.amount}}
                    </td>
                    <td class="table-light">
                        {{payment.created}}
                    </td>
                    <td class="table-light">
                        {{payment.pay_date}}
                    </td>
                    <td class="table-light">
                        <a class="btn btn-danger " href="{% url 'payments:delete_supplier_payment' payment.id %}">{% trans "Delete" %}</a>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>

        </div>
    </div>
</div>
{% endblock %}

buyorder/templates/buyorder/list_buyorder.html
{% extends 'home.html' %}
{% load static %}
{% load i18n %}
{% load search_pagination_url %}

{% block content %}
<br>
<div class="row">
    <div class="col-md">
        <div class="card card-body">
            <h5>{% trans "Buy Orders" %}</h5>
        </div>
        <br>
        <hr>
        <br>
        <div class="card card-body">

            <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
              <i class="fa-solid fa-magnifying-glass"></i>
            </button>
            <div class="collapse" id="collapseExample">
             <div class="card card-body">
                 <form method="get">
                                {{myFilter.form}}
                                <button class="btn btn-primary" type="submit">Search</button>
                 </form>
              </div>
            </div>
            <table id="table_id" class="table display text-center">

                <thead>
                <tr>
                    <th>{% trans "Order ID" %}</th>
                    <th>{% trans "Supplier" %}</th>
                    <th>{% trans "Phone" %}</th>
                    <th>{% trans "Date" %}</th>
                    <th>{% trans "Paid" %}</th>
                    <th>{% trans "HT" %}</th>
                    <th>{% trans "TVA" %}</th>
                    <th>{% trans "TTC" %}</th>
                    <th>{% trans "Debt" %}</th>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                {% for order in buyorders %}
                <tr>
                    <td>{{order.id}}</td>
                    <td>{{order.supplier}}</td>
                    <td>{{order.supplier.phone}}</td>
                    <td>{{order.order_date}}</td>
                    <td>{{order.paid}}</td>
                    <td>{{order.total_price}} {% trans "DZD" %}</td>
                    <td>{{order.get_tva}} {% trans "DZD" %}</td>
                    <td>{{order.get_ttc}} {% trans "DZD" %}</td>
                    <td>{{order.debt}} {% trans "DZD" %}</td>
                    <td>
                        {% if order.confirmed %}
                             <a class="btn btn-info " href="{% url 'buyorder:update_order' order.id %}">{% trans "Update" %}</a>
                        {% else %}
                             <a class="btn btn-success " href="{% url 'buyorder:buyorder_confirmation' order.id %}">{% trans "Confirm" %}</a>
                        {% endif %}
                    </td>
                    <td>
                        {% if order.debt > 0%}
                        <a class="btn btn-primary " href="{% url 'payments:create_supplier_payment' order.id %}">{% trans "PayDebt" %}</a>
                        {% endif %}
                    </td>
                    <td>
                        <a class="btn btn-warning " href="{% url 'buyorder:buyorder_details' order.id %}">{% trans "Details" %}</a>
                    </td>
                    <td>
                        <a class="btn btn-danger " href="{% url 'buyorder:buyorder_delete' order.id %}">{% trans "Delete" %}</a>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
            <!--  Pagination -->
                    {% if buyorders.has_other_pages %}
                        <nav aria-label="Page navigation example">
                            <ul class="pagination">
                                {% if buyorders.has_previous %}
                                    <li class="page-item">
                                        <a class="page-link"
                                        href="?{% param_replace page=buyorders.previous_page_number %}" aria-label="Previous">
                                            <span aria-hidden="true">&laquo;</span>
                                            <span class="sr-only">Previous</span>
                                        </a>
                                    </li>
                                {% else %}
                                    <li class="disabled page-item">
                                <a class="page-link"
                                   href="#" aria-label="Previous">
                                    <span aria-hidden="true">&laquo;</span>
                                    <span class="sr-only">Previous</span>
                                </a>
                            </li>
                                {% endif %}
                        {% for i in buyorders.paginator.page_range %}
                            {% if buyorders.number > 3 and forloop.first %}
                                <li class="page-item">
                                    <a class="page-link" href="?{% param_replace page=1 %}">
                                    1
                                        </a>
                                </li>
                                <li class="disabled">⋯</li>
                            {% endif %}
                            {% if buyorders.number == i %}
                                <li class="page-item active">
                                    <span>
                                        <a class="page-link" href="#">
                                        {{ i }}
                                            <span class="sr-only">(current)
                                            </span>
                                        </a>
                                    </span>
                                </li>
                            {% elif i > buyorders.number|add:'-3' and i < buyorders.number|add:'3' %}
                                <li class="page-item">
                                    <a class="page-link" href="?{% param_replace page=i %}">
                                        {{ i }}
                                    </a>
                                </li>
                            {% endif %}
                            {% if buyorders.paginator.num_pages > buyorders.number|add:'3' and forloop.last %}
                                <li>...</li>
                                <li class="page-item">
                                    <a class="page-link" href="?{% param_replace page=buyorders.paginator.num_pages %}">
                                    {{ buyorders.paginator.num_pages }}
                                        </a>
                                </li>
                            {% endif %}
                        {% endfor %}
                        {% if buyorders.has_next %}
                            <li class="page-item">
                                <a class="page-link"
                                   href="?{% param_replace page=buyorders.next_page_number %}" aria-label="Next">
                                    <span aria-hidden="true">&raquo;</span>
                                    <span class="sr-only">Next</span>
                                </a>
                            </li>
                        {% else %}
                            <li class="disabled page-item">
                                <a class="page-link disabled"
                                   href="#" aria-label="Next">
                                    <span aria-hidden="true">&raquo;</span>
                                    <span class="sr-only">Next</span>
                                </a>
                            </li>
                        {% endif %}
                    </ul>
                        </nav>
                    {% endif %}
            <!--  Pagination -->
        </div>
    </div>
</div>


{% endblock %}
{% block jsscript %}
<!-- custom javascript -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.jquery.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.min.css"/>

{% endblock %}

buyorder/templates/buyorder/list_buyorder_by_date.html
{% extends 'home.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load i18n %}
{% block content %}
<br>
<div class="row">
    <div class="col-md">
        <div class="card card-body">
            <h5>{% trans "Buy Orders" %}</h5>

        </div>
        <br>
        <br>
        <div class="card card-body">

            <form id="order-form" action="" method="post">

                    {% csrf_token %}
                <div class="form-group">
               <!-- date picker -->
                <label> {% trans "Pick a Date" %}</label>
                    <br>
                    {{dateform}}
                    <br>
                    <label >{% trans "Date:" %}</label>
                    {{chosen_date}}
                    <br>
            <input class="form-control btn btn-primary" type="submit" name="submit">
            </div>
            </form>
        </div>
        <div class="card card-body">
            <table id="table_id" class="table display text-center">
                <thead>
                <tr>
                    <th>{% trans "Order ID" %}</th>
                    <th>{% trans "Supplier" %}</th>
                    <th>{% trans "Phone" %}</th>
                    <th>{% trans "Date" %}</th>
                    <th>{% trans "Paid" %}</th>
                    <th>{% trans "HT" %}</th>
                    <th>{% trans "TVA" %}</th>
                    <th>{% trans "TTC" %}</th>
                    <th>{% trans "Debt" %}</th>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                {% for order in buyorders %}

                <tr>
                    <td>{{order.id}}</td>
                    <td>{{order.supplier}}</td>
                    <td>{{order.supplier.phone}}</td>
                    <td>{{order.order_date}}</td>
                    <td>{{order.paid}}</td>
                    <td>{{order.total_price}} {% trans "DZD" %}</td>
                    <td>{{order.get_tva}} {% trans "DZD" %}</td>
                    <td>{{order.get_ttc}} {% trans "DZD" %}</td>
                    <td>{{order.debt}} {% trans "DZD" %}</td>
                    <td>
                        {% if order.confirmed %}
                             <a class="btn btn-info " href="{% url 'buyorder:update_order' order.id %}">{% trans "Update" %}</a>
                        {% else %}
                             <a class="btn btn-success " href="{% url 'buyorder:buyorder_confirmation' order.id %}">{% trans "Confirm" %}</a>
                        {% endif %}
                    </td>
                    <td>
                        {% if order.debt > 0%}
                        <a class="btn btn-primary " href="{% url 'payments:create_supplier_payment' order.id %}">{% trans "PayDebt" %}</a>
                        {% endif %}
                    </td>
                    <td>
                        <a class="btn btn-warning " href="{% url 'buyorder:buyorder_details' order.id %}">{% trans "Details" %}</a>
                    </td>
                    <td>
                        <a class="btn btn-danger " href="{% url 'buyorder:buyorder_delete' order.id %}">{% trans "Delete" %}</a>
                    </td>
                </tr>

                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>


{% endblock %}
{% block jsscript %}
<!-- Date Picker-->
<script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />

<!-- custom javascript -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.jquery.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.min.css"/>
<!-- Data Table  -->
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.css">

<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.js"></script>
<!-- Date Picker-->
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>

<script type='text/javascript'>
    //Data Table init
    $(document).ready( function () {
    $('#table_id').DataTable();
    $('#table_supplier').DataTable();
} );

// Date Picker
$('input[name="date"]').daterangepicker();

</script>
{% endblock %}