buyorder/urls.py
from django.urls import path
from . import views

app_name = 'buyorder'

urlpatterns = [

    path('create_buyorder', views.create_buyorder, name='create_buyorder'),
    path('buyorder_list', views.buyorder_list, name='buyorder_list'),
    path('buyorder_list_by_date', views.buyorder_list_by_date, name='buyorder_list_by_date'),
    path('buyorder_confirmation/<str:pk>', views.buyorder_confirmation, name='buyorder_confirmation'),
    path('buyorder_pdf/<str:pk>', views.buyorder_pdf, name='buyorder_pdf'),
    path('buyorder_details/<str:pk>', views.buyorder_details, name='buyorder_details'),
    path('buyorderorder_list_by_supplier/<str:pk>', views.buyorderorder_list_by_supplier, name='buyorderorder_list_by_supplier'),
    path('buyorder_delete/<str:pk>', views.buyorder_delete, name='buyorder_delete'),
    path('update_order/<str:pk>', views.update_order, name='update_order'),
    path('confirm_all', views.confirm_all, name='confirm_all'),

    path('confirm_order_item_delete/<str:orderpk>/<str:itempk>', views.confirm_order_item_delete,
         name='confirm_order_item_delete'),


    # fixing dates
    path('fixing_dates', views.add_date_to_order, name='fixing_dates')
]

family/urls.py
from django.urls import path
from . import views

app_name = 'family'

urlpatterns = [

    path('family_list', views.family_list, name='family_list'),
    path('add_family', views.add_family, name='add_family'),
    path('update_family/<str:pk>', views.update_family, name='update_family'),
    path('delete_family/<str:pk>', views.delete_family, name='delete_family'),

]

mygarage/urls.py
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

from mygarage import settings

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    # the main ressource
    path('', include('accounts.urls', namespace='accounts')),
    # offline connection
    # path('', include('pwa.urls')),
    path('customer/', include('customer.urls', namespace='customer')),
    path('supplier/', include('supplier.urls', namespace='supplier')),
    path('payments/', include('payments.urls', namespace='payments')),
    path('family/', include('family.urls', namespace='family')),
    path('category/', include('category.urls', namespace='category')),
    path('stock/', include('stock.urls', namespace='stock')),
    path('product/', include('product.urls', namespace='product')),
    path('buyorder/', include('buyorder.urls', namespace='buyorder')),
    path('sellorder/', include('sellorder.urls', namespace='sellorder')),
    path('billing/', include('billing.urls', namespace='billing')),
    path('vehicule/', include('vehicule.urls', namespace='vehicule')),
    path('rdv/', include('rdv.urls', namespace='rdv')),
    path('caisse/', include('caisse.urls', namespace='caisse')),
    path('bank/', include('bank.urls', namespace='bank')),
    path('services/', include('services.urls', namespace='services')),
    path('employee/', include('employee.urls', namespace='employee')),
    # path('discount/', include('discount.urls', namespace='discount')),

    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path
from . import views

app_name = 'product'

urlpatterns = [
    path('all_product_list/', views.all_product_list, name='all_product_list'),
    # path('product_list/<str:pk>', views.product_list, name='product_list'),
    path('add_product', views.add_product, name='add_product'),
    path('delete_duplicated', views.delete_duplicated, name='delete_duplicated'),
    path('add_product_buyorder', views.add_product_buyorder, name='add_product_buyorder'),
    path('update_product/<str:pk>', views.update_product, name='update_product'),
    path('detail_product/<str:pk>', views.detail_product, name='detail_product'),
    path('delete_product/<str:pk>', views.delete_product, name='delete_product'),

]

rdv/urls.py
from django.urls import path
from . import views

app_name = 'rdv'

urlpatterns = [

    path('create_rdv_customer', views.create_rdv_customer, name='create_rdv_customer'),
    path('rdv_vehicle_list/<str:pk>', views.rdv_vehicle_list, name='rdv_vehicle_list'),
    path('rdv_list', views.rdv_list, name='rdv_list'),
    path('create_rdv/<str:pk>', views.create_rdv, name='create_rdv'),
    path('rdv_pdf/<str:pk>', views.rdv_pdf, name='rdv_pdf'),
    path('rdv_details/<str:pk>', views.rdv_details, name='rdv_details'),
    path('delete_rdv/<str:pk>', views.delete_rdv, name='delete_rdv'),

    # Panne
    path('create_panne', views.create_panne, name='create_panne'),
    path('panne_list', views.panne_list, name='panne_list'),
    path('update_panne/<str:pk>', views.update_panne, name='update_panne'),
    path('update_order_panne_list/<str:pk>', views.update_order_panne_list, name='update_order_panne_list'),
    path('confirm_order_panne_list/<str:pk>', views.confirm_order_panne_list, name='confirm_order_panne_list'),
    path('order_panne_list/<str:pk>', views.order_panne_list, name='order_panne_list'),
    path('delete_panne/<str:pk>', views.delete_panne, name='delete_panne'),

]

sellorder/urls.py
from django.urls import path
from . import views

app_name = 'sellorder'

urlpatterns = [

    path('sellorder_list', views.sellorder_list, name='sellorder_list'),
    path('sellorder_list_by_date', views.sellorder_list_by_date, name='sellorder_list_by_date'),
    path('sellorder_list_by_service', views.sellorder_list_by_service, name='sellorder_list_by_service'),
    path('facture_all', views.facture_all, name='facture_all'),

    path('performa_sellorder_list', views.performa_sellorder_list, name='performa_sellorder_list'),
    path('factured_sellorder_list', views.factured_sellorder_list, name='factured_sellorder_list'),

    path('confirm_order_performa/<str:pk>', views.confirm_order_performa, name='confirm_order_performa'),
    path('confirm_order/<str:pk>', views.confirm_order, name='confirm_order'),

    path('sellorder_facture/<str:pk>', views.sellorder_facture, name='sellorder_facture'),
    path('sellorder_facture_pdf/<str:pk>', views.sellorder_facture_pdf, name='sellorder_facture_pdf'),
    path('sellorder_facture_no_date_pdf/<str:pk>', views.sellorder_facture_no_date_pdf, name='sellorder_facture_no_date_pdf'),
    path('sellorder_facture_mo_pdf/<str:pk>', views.sellorder_facture_mo_pdf, name='sellorder_facture_mo_pdf'),
    path('sellorder_facture_mo_no_date_pdf/<str:pk>', views.sellorder_facture_mo_no_date_pdf, name='sellorder_facture_mo_no_date_pdf'),

    # print proforma
    path('sellorder_facture_proforma_pdf/<str:pk>', views.sellorder_facture_proforma_pdf, name='sellorder_facture_proforma_pdf'),
    path('sellorder_facture_proforma_mo_pdf/<str:pk>', views.sellorder_facture_proforma_mo_pdf, name='sellorder_facture_proforma_mo_pdf'),
    path('sellorder_facture_proforma_piece_pdf/<str:pk>', views.sellorder_facture_proforma_piece_pdf, name='sellorder_facture_proforma_piece_pdf'),

    path('bsb_sellorder_facture_proforma_pdf/<str:pk>', views.bsb_sellorder_facture_proforma_pdf, name='bsb_sellorder_facture_proforma_pdf'),
    path('nacer_sellorder_facture_proforma_pdf/<str:pk>', views.nacer_sellorder_facture_proforma_pdf, name='nacer_sellorder_facture_proforma_pdf'),
    path('ghezal_sellorder_facture_proforma_pdf/<str:pk>', views.ghezal_sellorder_facture_proforma_pdf, name='ghezal_sellorder_facture_proforma_pdf'),
    path('sellorder_facture_proforma_pdf_no_date/<str:pk>', views.sellorder_facture_proforma_pdf_no_date, name='sellorder_facture_proforma_pdf_no_date'),

    path('sellorder_list_by_customer/<str:pk>', views.sellorder_list_by_customer,
         name='sellorder_list_by_customer'),
    # print
    path('sellorder_pdf/<str:pk>/<str:credit>/<str:tva>', views.sellorder_pdf, name='sellorder_pdf'),
    path('sellorder_pour_pdf/<str:pk>/<str:credit>/<str:tva>', views.sellorder_pour_pdf, name='sellorder_pour_pdf'),
    path('sellorder_livraison_pdf/<str:pk>/<str:credit>/<str:tva>', views.sellorder_livraison_pdf, name='sellorder_livraison_pdf'),

    path('sellorder_details/<str:pk>', views.sellorder_details, name='sellorder_details'),
    path('sellorder_delete/<str:pk>', views.sellorder_delete, name='sellorder_delete'),
    path('update_order/<str:pk>', views.update_order, name='update_order'),
    path('update_order_performa/<str:pk>', views.update_order_performa, name='update_order_performa'),
    path('order_to_performa/<str:pk>', views.order_to_performa, name='order_to_performa'),

    path('order_item_delete/<str:orderpk>/<str:itempk>', views.order_item_delete, name='order_item_delete'),
    path('confirm_order_item_delete/<str:orderpk>/<str:itempk>', views.confirm_order_item_delete, name='confirm_order_item_delete'),
    path('proforma_item_delete/<str:orderpk>/<str:itempk>', views.proforma_item_delete, name='proforma_item_delete'),

    path('order_panne_delete/<str:orderpk>/<str:itempk>', views.order_panne_delete, name='order_panne_delete'),
    path('confirm_order_panne_delete/<str:orderpk>/<str:itempk>', views.confirm_order_panne_delete, name='confirm_order_panne_delete'),
    path('proforma_panne_delete/<str:orderpk>/<str:itempk>', views.proforma_panne_delete, name='proforma_panne_delete'),

    path('confirm_order_service_delete/<str:orderpk>/<str:itempk>', views.confirm_order_service_delete, name='confirm_order_service_delete'),
    path('order_service_delete/<str:orderpk>/<str:itempk>', views.order_service_delete, name='order_service_delete'),
    path('proforma_service_delete/<str:orderpk>/<str:itempk>', views.proforma_service_delete, name='proforma_service_delete'),

    path('get_orders_pannes', views.get_orders_pannes, name='get_orders_pannes'),
    path('get_orders_pieces', views.get_orders_pieces, name='get_orders_pieces'),
    path('get_orders_pannes_payed', views.get_orders_pannes_payed, name='get_orders_pannes_payed'),
    path('get_orders_pieces_payed', views.get_orders_pieces_payed, name='get_orders_pieces_payed'),

    # order debt fixing
    path('order_fix_debt', views.order_fix_debt, name='order_fix_debt'),

]

product/models.py
from django.db import models
from category.models import Category


# Create your models here.
class Product(models.Model):
    # add buy price or production price
    # category = models.ForeignKey(Category, null=True, on_delete=models.CASCADE)
    brand = models.CharField(max_length=250, null=True)
    name = models.CharField(max_length=250, null=True)
    ref = models.CharField(max_length=250, null=True)
    desc = models.CharField(max_length=250, null=True, blank=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True, )
    buyprice = models.DecimalField(max_digits=10, null=True, decimal_places=2, default=0)
    sellprice = models.DecimalField(max_digits=10, null=True, decimal_places=2, default=0)
    # sellpricesemi_grou = models.DecimalField(max_digits=10, null=True, decimal_places=2, default=0)
    # sellpricegrou = models.DecimalField(max_digits=10, null=True, decimal_places=2, default=0)
    # sellspecialprice = models.DecimalField(max_digits=10, null=True, decimal_places=2, default=0)
    alert_quantity = models.PositiveIntegerField(default=1, blank=True, null=True)
    # box_quantity = models.PositiveIntegerField(default=1)
    stock = models.ForeignKey('stock.Stock', blank=False, null=False, on_delete=models.CASCADE, default=1)

    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def __str__(self):
        return self.name

product/forms.py
from django.forms import ModelForm, modelformset_factory
from django import forms
from product.models import Product


class ProductForm(ModelForm):
    class Meta:
        model = Product

        fields = [
            # 'category',
            'brand', 'name', 'ref', 'desc', 'image', 'stock', 'sellprice',
            'buyprice',
        ]

product/templates/product/add_product.html
{% extends 'home.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<br>

<div class="container">
    <div class="row">
    <div class="col-md-3 col-sm-1">

    </div>
    <div class="col-md-6 col-sm-12">
        <div class="card card-body">

            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{productform|crispy}}
                <input class="btn btn-primary" type="submit" name="submit">
            </form>
        </div>
        {% if productform.errors %}
        {% for field in productform %}
        {% for error in field.errors %}
        <div class="alert alert-danger">
            <strong>{{field.label}} {{ error|escape }}</strong>
        </div>
        {% endfor %}
        {% endfor %}
        {% for error in productform.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
        {% endfor %}
        {% endif %}


    </div>
    <div class="col-md-3 col-sm-1">

    </div>
</div>
</div>

<script>

	</script>
{% endblock %}

product/templates/product/all_product_list.html
{% extends 'home.html' %}
{% load static %}
{% load i18n %}
{% load search_pagination_url %}

{% block content %}
<br>
<div class="container">
    <div class="row">
    <div class="col-md">
        <div class="card card-body">
            <h5>{% trans "Products" %}</h5>
        </div>
        <div class="card card-body">
            <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
              <i class="fa-solid fa-magnifying-glass"></i>
            </button>
            <div class="collapse" id="collapseExample">
             <div class="card card-body">
                 <form method="get">
                                {{myFilter.form}}
                                <button class="btn btn-primary" type="submit">Search</button>
                 </form>
              </div>
            </div>
            <table id="table_id" class="display text-center table">
                <thead>
                <tr>
                    <th>{% trans "Image" %}</th>
                    <th>{% trans "Brand" %}</th>
                    <th>{% trans "Name" %}</th>
                    <th>{% trans "Ref" %}</th>
                    <th>{% trans "Sell Price" %}</th>
                    <th>{% trans "Buy Price" %}</th>
                    <th>{% trans "Stock" %}</th>
                    <th></th>
                    <th></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                {% for prod in products %}
                <tr>
                   <td>
                       <img class="card-img" style="width: 100%; height: 20vh;" src="{% if prod.image %}{{prod.image.url}}{% else %} {% static 'img/no_image.png' %}{% endif %}" alt="{{prod.name}}">
                   </td>
                    <td>
                       {{prod.brand}}
                   </td>
                    <td>
                       {{prod.name}}
                   </td>
                    <td>
                       {{prod.ref}}
                   </td>
                    <td>
                       {{prod.sellprice}} {% trans "DZD" %}
                   </td>
                    <td>
                       {{prod.buyprice}} {% trans "DZD" %}
                   </td>
                    <td>
                       {{prod.stock}}
                   </td>
                    <td>
                        <a class="btn btn-success " href="{% url 'product:update_product' prod.id %}">{% trans "Update" %}</a>
                    </td>
                    <td>
                        <a class="btn btn-warning " href="{% url 'product:detail_product' prod.id %}">{% trans "Details" %}</a>
                    </td>
                    <td>
                        <a class="btn btn-danger " href="{% url 'product:delete_product' prod.id %}">{% trans "Delete" %}</a>
                    </td>
                </tr>
                {% endfor %}
                </tbody>

            </table>
            <!--  Pagination -->
                    {% if products.has_other_pages %}
                        <nav aria-label="Page navigation example">
                            <ul class="pagination">
                                {% if products.has_previous %}
                                    <li class="page-item">
                                        <a class="page-link"
                                        href="?{% param_replace page=products.previous_page_number %}" aria-label="Previous">
                                            <span aria-hidden="true">&laquo;</span>
                                            <span class="sr-only">Previous</span>
                                        </a>
                                    </li>
                                {% else %}
                                    <li class="disabled page-item">
                                <a class="page-link"
                                   href="#" aria-label="Previous">
                                    <span aria-hidden="true">&laquo;</span>
                                    <span class="sr-only">Previous</span>
                                </a>
                            </li>
                                {% endif %}
                        {% for i in products.paginator.page_range %}
                            {% if products.number > 3 and forloop.first %}
                                <li class="page-item">
                                    <a class="page-link" href="?{% param_replace page=1 %}">
                                    1
                                        </a>
                                </li>
                                <li class="disabled">⋯</li>
                            {% endif %}
                            {% if products.number == i %}
                                <li class="page-item active">
                                    <span>
                                        <a class="page-link" href="#">
                                        {{ i }}
                                            <span class="sr-only">(current)
                                            </span>
                                        </a>
                                    </span>
                                </li>
                            {% elif i > products.number|add:'-3' and i < products.number|add:'3' %}
                                <li class="page-item">
                                    <a class="page-link" href="?{% param_replace page=i %}">
                                        {{ i }}
                                    </a>
                                </li>
                            {% endif %}
                            {% if products.paginator.num_pages > products.number|add:'3' and forloop.last %}
                                <li>...</li>
                                <li class="page-item">
                                    <a class="page-link" href="?{% param_replace page=products.paginator.num_pages %}">
                                    {{ products.paginator.num_pages }}
                                        </a>
                                </li>
                            {% endif %}
                        {% endfor %}
                        {% if products.has_next %}
                            <li class="page-item">
                                <a class="page-link"
                                   href="?{% param_replace page=products.next_page_number %}" aria-label="Next">
                                    <span aria-hidden="true">&raquo;</span>
                                    <span class="sr-only">Next</span>
                                </a>
                            </li>
                        {% else %}
                            <li class="disabled page-item">
                                <a class="page-link disabled"
                                   href="#" aria-label="Next">
                                    <span aria-hidden="true">&raquo;</span>
                                    <span class="sr-only">Next</span>
                                </a>
                            </li>
                        {% endif %}
                    </ul>
                        </nav>
                    {% endif %}
            <!--  Pagination -->
        </div>
    </div>
</div>

</div>
{% endblock %}
{% block jsscript %}
<!-- custom javascript -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.jquery.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.min.css"/>
{% endblock %}

product/templates/product/delete.html
{% extends 'home.html' %}
{% load static %}
{% load i18n %}
{% block content %}
<br>

<div class="container">
    <div class="row">
    <div class="col-md-3">
    </div>
    <div class="col-md-6">
        <div class="card card-body">
            <P>{% trans "ARE YOU SURE YOU WANT TO DELETE" %} {{product}}</P>
            <form action="{% url 'product:delete_product' product.id %}" method="post">

                {% csrf_token %}
                <input class="btn btn-danger" type="submit" name="Confirm">
                <a class="btn btn-warning" href="{% url 'family:family_list' %}">{% trans "Cancel" %}</a>
            </form>
        </div>
    </div>
    <div class="col-md-3">
    </div>
</div>
</div>


<script>

</script>
{% endblock %}

product/templates/product/details.html
{% extends 'home.html' %}
{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block content %}
<br>
<div class="row">
    <div class="col-md">
        <div class="card card-body">
            <h5>{% trans "Sell Orders" %}</h5>
        </div>
         <div class="card card-body">

            <form id="order-form" action="" method="post">

                    {% csrf_token %}
                <div class="form-group">
               <!-- date picker -->
                <label> {% trans "Pick a Date" %}</label>
                    <br>
                    {{dateform}}
                    <br>
                    <label >{% trans "Date:" %}</label>
                    {{chosen_date}}
                    <br>
            <input class="form-control btn btn-primary" type="submit" name="submit">
            </div>
            </form>
        </div>
        <div class="card card-body bg-primary">
            <h5 class=" text-center text-white">{{product}} : {{sell_quantity}}</h5>
        </div>
        <div class="card card-body">
            <table id="table_id" class="table display text-center">
                <thead>
                <tr>
                    <th>{% trans "Order ID" %}</th>
                    <th>{% trans "Customer" %}</th>
                    <th>{% trans "Date" %}</th>
                    <th>{% trans "Bill" %}</th>
                    <th>{% trans "Quantity" %}</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                {% for order, item, quantity in final_list %}

                <tr>
                    <td>{{order.id}}</td>
                    <td>{{order.customer}}</td>
                    <td>{{order.order_date}}</td>
                    <td>{{order.factured}}</td>
                    <td>{{quantity}}</td>
                    <td>
                         <a class="btn btn-warning " href="{% url 'sellorder:sellorder_details' order.id %}">{% trans "Details" %}</a>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <br>
        <div class="card card-body">
            <h5>{% trans "Buy Orders" %}</h5>
        </div>
        <div class="card card-body bg-danger">
            <h5 class=" text-center text-white">{{product}} : {{buy_quantity}}</h5>
        </div>
        <div class="card card-body">
            <table id="table_buyorder" class="table display text-center">
                <thead>
                <tr>
                    <th>{% trans "Order ID" %}</th>
                    <th>{% trans "Supplier" %}</th>
                    <th>{% trans "Date" %}</th>
                    <th>{% trans "Quantity" %}</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                {% for order, item, quantity in final_buylist %}

                <tr>
                    <td>{{order.id}}</td>
                    <td>{{order.supplier}}</td>
                    <td>{{order.order_date}}</td>
                    <td>{{quantity}}</td>
                    <td>
                        <a class="btn btn-warning " href="{% url 'buyorder:buyorder_details' order.id %}">Details</a>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock %}
{% block jsscript %}
<!-- Date Picker-->
<script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />


<!-- custom javascript -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.jquery.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.min.css"/>
<!-- Data Table  -->
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.css">

<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.js"></script>
<!-- Date Picker-->
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>

<script type='text/javascript'>
    //Data Table init
    $(document).ready( function () {
    $('#table_id').DataTable();
    $('#table_buyorder').DataTable();
} );

// Date Picker
$('input[name="date"]').daterangepicker();


</script>
{% endblock %}

product/templates/product/list_product.html
{% extends 'home.html' %}
{% load static %}
{% load i18n %}
{% block content %}
<br>
<div class="container">
    <div class="row">
    <div class="col-md">
        <div class="card card-body">
            <h5>{% trans "Products</h5>
        </div>
        <div class="card card-body">
            <table class="table">
                <tr>
                    <th>{% trans "Image" %}</th>
                    <th>{% trans "Name" %}</th>
                    <th>{% trans "Category" %}</th>
                    <th>{% trans "Sell Price" %}</th>
                    <th>{% trans "Buy Price" %}</th>
                    <th>{% trans "Stock" %}</th>
                </tr>

                {% for prod in products %}
                <tr>
                   <td>
                       <img class="card-img" style="width: 100%; height: 20vh;" src="{{prod.image.url}}" alt="{{prod.name}}">
                   </td>
                    <td>
                       {{prod.name}}
                   </td>
                    <td>
                       {{prod.category}}
                   </td>
                    <td>
                       {{prod.sellprice}} {% trans "DZD" %}
                   </td>
                    <td>
                       {{prod.buyprice}} {% trans "DZD" %}
                   </td>
                    <td>
                       {{prod.stock}}
                   </td>
                    <td>
                        <a class="btn btn-success " href="{% url 'product:update_product' prod.id %}">{% trans "Update" %}</a>
                    </td>
                    <td>
                        <a class="btn btn-danger " href="{% url 'product:delete_product' prod.id %}">{% trans "Delete" %}</a>
                    </td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>

</div>
{% endblock %}