mygarage/urls.py
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

from mygarage import settings

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    # the main ressource
    path('', include('accounts.urls', namespace='accounts')),
    # offline connection
    # path('', include('pwa.urls')),
    path('customer/', include('customer.urls', namespace='customer')),
    path('supplier/', include('supplier.urls', namespace='supplier')),
    path('payments/', include('payments.urls', namespace='payments')),
    path('family/', include('family.urls', namespace='family')),
    path('category/', include('category.urls', namespace='category')),
    path('stock/', include('stock.urls', namespace='stock')),
    path('product/', include('product.urls', namespace='product')),
    path('buyorder/', include('buyorder.urls', namespace='buyorder')),
    path('sellorder/', include('sellorder.urls', namespace='sellorder')),
    path('billing/', include('billing.urls', namespace='billing')),
    path('vehicule/', include('vehicule.urls', namespace='vehicule')),
    path('rdv/', include('rdv.urls', namespace='rdv')),
    path('caisse/', include('caisse.urls', namespace='caisse')),
    path('bank/', include('bank.urls', namespace='bank')),
    path('services/', include('services.urls', namespace='services')),
    path('employee/', include('employee.urls', namespace='employee')),
    # path('discount/', include('discount.urls', namespace='discount')),

    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payments/urls.py
from django.urls import path
from . import views

app_name = 'payments'

urlpatterns = [
    # Customer
    path('create_customer_payment/<str:pk>', views.create_customer_payment, name='create_customer_payment'),
    path('create_customer_cheque/<str:pk>', views.create_customer_cheque, name='create_customer_cheque'),
    path('create_customer_verment/<str:pk>', views.create_customer_verment, name='create_customer_verment'),
    path('delete_customer_payment/<str:pk>', views.delete_customer_payment, name='delete_customer_payment'),
    path('customer_payment_list', views.customer_payment_list, name='customer_payment_list'),

    # Supplier
    path('create_supplier_payment/<str:pk>', views.create_supplier_payment, name='create_supplier_payment'),
    path('create_supplier_payment_by_supplier/<str:pk>', views.create_supplier_payment_by_supplier, name='create_supplier_payment_by_supplier'),
    path('create_supplier_cheque/<str:pk>', views.create_supplier_cheque, name='create_supplier_cheque'),
    path('supplier_payment_list', views.supplier_payment_list, name='supplier_payment_list'),
    path('delete_supplier_payment/<str:pk>', views.delete_supplier_payment, name='delete_supplier_payment'),
    path('delete_supplier_by_supplier_payment/<str:pk>', views.delete_supplier_by_supplier_payment,
         name='delete_supplier_by_supplier_payment'),

    # Service
    path('create_service_payment/<str:pk>', views.create_service_payment, name='create_service_payment'),
    path('service_payment_list', views.service_payment_list, name='service_payment_list'),
    path('delete_service_payment/<str:pk>', views.delete_service_payment, name='delete_service_payment'),

]

rdv/urls.py
from django.urls import path
from . import views

app_name = 'rdv'

urlpatterns = [

    path('create_rdv_customer', views.create_rdv_customer, name='create_rdv_customer'),
    path('rdv_vehicle_list/<str:pk>', views.rdv_vehicle_list, name='rdv_vehicle_list'),
    path('rdv_list', views.rdv_list, name='rdv_list'),
    path('create_rdv/<str:pk>', views.create_rdv, name='create_rdv'),
    path('rdv_pdf/<str:pk>', views.rdv_pdf, name='rdv_pdf'),
    path('rdv_details/<str:pk>', views.rdv_details, name='rdv_details'),
    path('delete_rdv/<str:pk>', views.delete_rdv, name='delete_rdv'),

    # Panne
    path('create_panne', views.create_panne, name='create_panne'),
    path('panne_list', views.panne_list, name='panne_list'),
    path('update_panne/<str:pk>', views.update_panne, name='update_panne'),
    path('update_order_panne_list/<str:pk>', views.update_order_panne_list, name='update_order_panne_list'),
    path('confirm_order_panne_list/<str:pk>', views.confirm_order_panne_list, name='confirm_order_panne_list'),
    path('order_panne_list/<str:pk>', views.order_panne_list, name='order_panne_list'),
    path('delete_panne/<str:pk>', views.delete_panne, name='delete_panne'),

]

sellorder/urls.py
from django.urls import path
from . import views

app_name = 'sellorder'

urlpatterns = [

    path('sellorder_list', views.sellorder_list, name='sellorder_list'),
    path('sellorder_list_by_date', views.sellorder_list_by_date, name='sellorder_list_by_date'),
    path('sellorder_list_by_service', views.sellorder_list_by_service, name='sellorder_list_by_service'),
    path('facture_all', views.facture_all, name='facture_all'),

    path('performa_sellorder_list', views.performa_sellorder_list, name='performa_sellorder_list'),
    path('factured_sellorder_list', views.factured_sellorder_list, name='factured_sellorder_list'),

    path('confirm_order_performa/<str:pk>', views.confirm_order_performa, name='confirm_order_performa'),
    path('confirm_order/<str:pk>', views.confirm_order, name='confirm_order'),

    path('sellorder_facture/<str:pk>', views.sellorder_facture, name='sellorder_facture'),
    path('sellorder_facture_pdf/<str:pk>', views.sellorder_facture_pdf, name='sellorder_facture_pdf'),
    path('sellorder_facture_no_date_pdf/<str:pk>', views.sellorder_facture_no_date_pdf, name='sellorder_facture_no_date_pdf'),
    path('sellorder_facture_mo_pdf/<str:pk>', views.sellorder_facture_mo_pdf, name='sellorder_facture_mo_pdf'),
    path('sellorder_facture_mo_no_date_pdf/<str:pk>', views.sellorder_facture_mo_no_date_pdf, name='sellorder_facture_mo_no_date_pdf'),

    # print proforma
    path('sellorder_facture_proforma_pdf/<str:pk>', views.sellorder_facture_proforma_pdf, name='sellorder_facture_proforma_pdf'),
    path('sellorder_facture_proforma_mo_pdf/<str:pk>', views.sellorder_facture_proforma_mo_pdf, name='sellorder_facture_proforma_mo_pdf'),
    path('sellorder_facture_proforma_piece_pdf/<str:pk>', views.sellorder_facture_proforma_piece_pdf, name='sellorder_facture_proforma_piece_pdf'),

    path('bsb_sellorder_facture_proforma_pdf/<str:pk>', views.bsb_sellorder_facture_proforma_pdf, name='bsb_sellorder_facture_proforma_pdf'),
    path('nacer_sellorder_facture_proforma_pdf/<str:pk>', views.nacer_sellorder_facture_proforma_pdf, name='nacer_sellorder_facture_proforma_pdf'),
    path('ghezal_sellorder_facture_proforma_pdf/<str:pk>', views.ghezal_sellorder_facture_proforma_pdf, name='ghezal_sellorder_facture_proforma_pdf'),
    path('sellorder_facture_proforma_pdf_no_date/<str:pk>', views.sellorder_facture_proforma_pdf_no_date, name='sellorder_facture_proforma_pdf_no_date'),

    path('sellorder_list_by_customer/<str:pk>', views.sellorder_list_by_customer,
         name='sellorder_list_by_customer'),
    # print
    path('sellorder_pdf/<str:pk>/<str:credit>/<str:tva>', views.sellorder_pdf, name='sellorder_pdf'),
    path('sellorder_pour_pdf/<str:pk>/<str:credit>/<str:tva>', views.sellorder_pour_pdf, name='sellorder_pour_pdf'),
    path('sellorder_livraison_pdf/<str:pk>/<str:credit>/<str:tva>', views.sellorder_livraison_pdf, name='sellorder_livraison_pdf'),

    path('sellorder_details/<str:pk>', views.sellorder_details, name='sellorder_details'),
    path('sellorder_delete/<str:pk>', views.sellorder_delete, name='sellorder_delete'),
    path('update_order/<str:pk>', views.update_order, name='update_order'),
    path('update_order_performa/<str:pk>', views.update_order_performa, name='update_order_performa'),
    path('order_to_performa/<str:pk>', views.order_to_performa, name='order_to_performa'),

    path('order_item_delete/<str:orderpk>/<str:itempk>', views.order_item_delete, name='order_item_delete'),
    path('confirm_order_item_delete/<str:orderpk>/<str:itempk>', views.confirm_order_item_delete, name='confirm_order_item_delete'),
    path('proforma_item_delete/<str:orderpk>/<str:itempk>', views.proforma_item_delete, name='proforma_item_delete'),

    path('order_panne_delete/<str:orderpk>/<str:itempk>', views.order_panne_delete, name='order_panne_delete'),
    path('confirm_order_panne_delete/<str:orderpk>/<str:itempk>', views.confirm_order_panne_delete, name='confirm_order_panne_delete'),
    path('proforma_panne_delete/<str:orderpk>/<str:itempk>', views.proforma_panne_delete, name='proforma_panne_delete'),

    path('confirm_order_service_delete/<str:orderpk>/<str:itempk>', views.confirm_order_service_delete, name='confirm_order_service_delete'),
    path('order_service_delete/<str:orderpk>/<str:itempk>', views.order_service_delete, name='order_service_delete'),
    path('proforma_service_delete/<str:orderpk>/<str:itempk>', views.proforma_service_delete, name='proforma_service_delete'),

    path('get_orders_pannes', views.get_orders_pannes, name='get_orders_pannes'),
    path('get_orders_pieces', views.get_orders_pieces, name='get_orders_pieces'),
    path('get_orders_pannes_payed', views.get_orders_pannes_payed, name='get_orders_pannes_payed'),
    path('get_orders_pieces_payed', views.get_orders_pieces_payed, name='get_orders_pieces_payed'),

    # order debt fixing
    path('order_fix_debt', views.order_fix_debt, name='order_fix_debt'),

]

sellorder/models.py
import decimal
from decimal import Decimal
from unicodedata import decimal

from django.db import models

# Create your models here.
from customer.models import Customer
from rdv.models import Panne
from services.models import Service, ServiceProvider
from stock.models import StockProduct
from vehicule.models import Vehicle


class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.DO_NOTHING, related_name="orders")
    vehicle = models.ForeignKey(Vehicle, on_delete=models.DO_NOTHING, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    debt = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True, default=0)
    timbre = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True, default=0)
    total_price = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True, default=0)
    discount_amount = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True, default=0)
    paid = models.BooleanField(default=False)
    order_tva = models.PositiveIntegerField(default=0)
    confirmed = models.BooleanField(default=False)
    factured = models.BooleanField(default=False)
    order_date = models.DateField(null=True, blank=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return f'Order {self.id}'

    def get_total_cost(self):
        return round(sum(item.get_cost() for item in self.items.all()), 2)

    def get_total_benefit(self):
        return round(sum(item.get_benefit() for item in self.items.all()), 2)

    def get_total_panne(self):
        return round(sum(item.get_cost() for item in self.pannes.all()), 2)

    def get_total_service(self):
        return round(sum(item.get_cost() for item in self.services.all()), 2)

    def get_total_item_panne(self):
        return round(sum(item.get_cost() for item in self.pannes.all()) + self.get_total_cost() + \
                     sum(item.get_cost() for item in self.services.all()), 2)

    def get_tva(self):
        return round(self.get_total_item_panne() * Decimal(self.order_tva / 100), 2)

    def get_ttc(self):
        return round(self.get_total_item_panne() + self.get_tva() - self.discount_amount + self.timbre, 2)

    def get_debt(self):
        payments = round(sum(item.amount for item in self.payments_items.all()), 2)
        return self.get_ttc() - payments


class OrderItem(models.Model):
    order = models.ForeignKey(Order,
                              related_name='items',
                              on_delete=models.CASCADE)
    stockproduct = models.ForeignKey(StockProduct,
                                     related_name='order_item',
                                     on_delete=models.SET_NULL, null=True, blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    buy_price = models.DecimalField(max_digits=10, decimal_places=2, )
    quantity = models.DecimalField(max_digits=10, decimal_places=2, default=0)

    def __str__(self):
        return str(self.id)

    def get_cost(self):
        return round(self.price * self.quantity, 2)

    def get_benefit(self):
        if self.buy_price == 0:
            if self.stockproduct:
                self.buy_price = self.stockproduct.buy_price
                self.save()
        return round((self.price - self.buy_price) * self.quantity, 2)


class PanneItem(models.Model):
    order = models.ForeignKey(Order,
                              related_name='pannes',
                              on_delete=models.CASCADE)
    panne = models.ForeignKey(Panne, related_name='order_panne',
                              on_delete=models.DO_NOTHING, null=True, blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return str(self.id)

    def get_cost(self):
        return self.price


class ServiceItem(models.Model):
    order = models.ForeignKey(Order,
                              related_name='services',
                              on_delete=models.CASCADE)
    service = models.ForeignKey(Service, related_name='order_service',
                                on_delete=models.DO_NOTHING, null=True, blank=True)
    provider = models.ForeignKey(ServiceProvider, related_name='provided_item',
                                 on_delete=models.DO_NOTHING, null=True, blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    charge = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)

    def __str__(self):
        return str(self.id)

    def get_cost(self):
        return Decimal(self.price) + Decimal(0 if self.charge is None else self.charge)


# Facture
class SellOrderFacture(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

sellorder/forms.py
from django.forms import ModelForm
from django import forms


class PeriodForm(forms.Form):
    start_date = forms.DateTimeField(initial="2021-01-01",
                                     widget=forms.DateInput(attrs={
                                         'class': 'form-control datepicker', 'type': 'date'
                                     })
                                     )
    end_date = forms.DateTimeField(initial="2021-01-01",
                                   widget=forms.DateInput(attrs={
                                       'class': 'form-control datepicker', 'type': 'date'
                                   })
                                   )

sellorder/templates/sellorder/list_sellorder.html
{% extends 'home.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load i18n %}
{% load search_pagination_url %}

{% block content %}
<br>
<div class="row">
    <div class="col-md">
        <div class="card card-body">
            {% if list_type == 1 %}
            <h1 class="text-primary"><i class="fa-solid fa-sheet-plastic"></i> {% trans "Sell Orders" %} </h1>
            {% endif %}
            {% if list_type == 2 %}
            <h5>{% trans "Facture List" %}</h5>
            {% endif %}
            {% if list_type == 3 %}
            <h5>{% trans "Proforma list" %}</h5>
            {% endif %}
        </div>
        <div class="card card-body">
            <div class="row">
                    <div class="col">
                        <div class="card card-body">
                            <form method="get">
                                {{myFilter.form}}
                                <button class="btn btn-primary" type="submit">Search</button>
                            </form>
                        </div>
                    </div>
                </div>
        </div>
        <div class="card card-body">
            <table id="table_id" class="table display text-center">
                <thead>
                <tr>
                    <th>{% trans "Order ID" %}</th>
                    <th>{% trans "Customer" %}</th>
                    <th>{% trans "Date" %}</th>
                    <th>{% trans "Vehicle" %}</th>
                    <th>{% trans "Total Piece" %}</th>
                    <th>{% trans "Total Panne" %}</th>
                    <th>{% trans "HT" %}</th>
                    <th>{% trans "TVA" %}</th>
                    <th>{% trans "Discount" %}</th>
                    <th>{% trans "TTC" %}</th>
                    <th>{% trans "Debt" %}</th>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                {% for order in sellorders %}

                <tr>
                    <td>{{order.id}}</td>
                    <td>{{order.customer}}</td>
                    <td>{{order.order_date}}</td>
                    <td>{{order.vehicle}}</td>
                    <td>{{order.get_total_cost}} {% trans "DZD" %}</td>
                    <td>{{order.get_total_panne}} {% trans "DZD" %}</td>
                    <td>{{order.get_total_item_panne}} {% trans "DZD" %}</td>
                    <td>{{order.get_tva}} {% trans "DZD" %}</td>
                    <td>{{order.discount_amount}} {% trans "DZD" %}</td>
                    <td>{{order.get_ttc}} {% trans "DZD" %}</td>
                    <td>{{order.debt}} {% trans "DZD" %}</td>


                    <td>
                        {% if order.factured %}
                        {% else %}
                             <a class="btn btn-primary " href="{% url 'sellorder:sellorder_facture' order.id %}">{% trans "Facture" %}</a>
                        {% endif %}
                    </td>
                    <td>
                        {% if order.confirmed %}
                             <a class="btn btn-info " href="{% url 'sellorder:update_order' order.id %}">{% trans "Update" %}</a>
                        {% else %}
                             <a class="btn btn-success " href="{% url 'sellorder:confirm_order' order.id %}">{% trans "Confirm" %}</a>
                        {% endif %}
                    </td>
                    <td>
                        {% if order.debt > 0 and order.confirmed %}
                            <a class="btn btn-primary " href="{% url 'payments:create_customer_payment' order.id %}">{% trans "PayDebt" %}</a>
                        {% else %}
                        {% if not order.confirmed %}
                            <a class="btn btn-primary " href="{% url 'sellorder:update_order_performa' order.id %}">{% trans "Update" %}</a>
                        {% endif %}
                        {% endif %}
                    </td>

                    <td>
                           <a class="btn btn-warning " href="{% url 'sellorder:sellorder_details' order.id %}">{% trans "Details" %}</a>
                    </td>
                    <td>
                           <a class="btn btn-danger " href="{% url 'sellorder:sellorder_delete' order.id %}">{% trans "Delete" %}</a>
                    </td>
                </tr>

                {% endfor %}
                </tbody>
            </table>
            <br>
             <!--  Pagination -->
                    {% if sellorders.has_other_pages %}
                        <nav aria-label="Page navigation example">
                            <ul class="pagination">
                                {% if sellorders.has_previous %}
                                    <li class="page-item">
                                        <a class="page-link"
                                        href="?{% param_replace page=sellorders.previous_page_number %}" aria-label="Previous">
                                            <span aria-hidden="true">&laquo;</span>
                                            <span class="sr-only">Previous</span>
                                        </a>
                                    </li>
                                {% else %}
                                    <li class="disabled page-item">
                                <a class="page-link"
                                   href="#" aria-label="Previous">
                                    <span aria-hidden="true">&laquo;</span>
                                    <span class="sr-only">Previous</span>
                                </a>
                            </li>
                                {% endif %}
                        {% for i in sellorders.paginator.page_range %}
                            {% if sellorders.number > 3 and forloop.first %}
                                <li class="page-item">
                                    <a class="page-link" href="?{% param_replace page=1 %}">
                                    1
                                        </a>
                                </li>
                                <li class="disabled">⋯</li>
                            {% endif %}
                            {% if sellorders.number == i %}
                                <li class="page-item active">
                                    <span>
                                        <a class="page-link" href="#">
                                        {{ i }}
                                            <span class="sr-only">(current)
                                            </span>
                                        </a>
                                    </span>
                                </li>
                            {% elif i > sellorders.number|add:'-3' and i < sellorders.number|add:'3' %}
                                <li class="page-item">
                                    <a class="page-link" href="?{% param_replace page=i %}">
                                        {{ i }}
                                    </a>
                                </li>
                            {% endif %}
                            {% if sellorders.paginator.num_pages > sellorders.number|add:'3' and forloop.last %}
                                <li>...</li>
                                <li class="page-item">
                                    <a class="page-link" href="?{% param_replace page=sellorders.paginator.num_pages %}">
                                    {{ sellorders.paginator.num_pages }}
                                        </a>
                                </li>
                            {% endif %}
                        {% endfor %}
                        {% if sellorders.has_next %}
                            <li class="page-item">
                                <a class="page-link"
                                   href="?{% param_replace page=sellorders.next_page_number %}" aria-label="Next">
                                    <span aria-hidden="true">&raquo;</span>
                                    <span class="sr-only">Next</span>
                                </a>
                            </li>
                        {% else %}
                            <li class="disabled page-item">
                                <a class="page-link disabled"
                                   href="#" aria-label="Next">
                                    <span aria-hidden="true">&raquo;</span>
                                    <span class="sr-only">Next</span>
                                </a>
                            </li>
                        {% endif %}
                    </ul>
                        </nav>
                    {% endif %}
            <!--  Pagination -->
        </div>
    </div>
</div>


{% endblock %}
{% block jsscript %}
<!-- Date Picker-->
<script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />

<!-- custom javascript -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.jquery.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.min.css"/>

<!-- Date Picker-->
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>

<script type='text/javascript'>



</script>
{% endblock %}

sellorder/templates/sellorder/list_sellorder_by_date.html
{% extends 'home.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load i18n %}
{% block content %}
<br>
<div class="row">
    <div class="col-md">
        <div class="card card-body">
            {% if list_type == 1 %}
            <h5>{% trans "Sell Orders" %}</h5>
            {% endif %}
            {% if list_type == 2 %}
            <h5>{% trans "Facture List" %}</h5>
            {% endif %}
            {% if list_type == 3 %}
            <h5>{% trans "Proforma list" %}</h5>
            {% endif %}
        </div>
        <br>
        <br>
        <div class="card card-body">

            <form id="order-form" action="" method="post">

                    {% csrf_token %}
                <div class="form-group">
               <!-- date picker -->
                <label> {% trans "Pick a Date" %}</label>
                    <br>
                    {{dateform}}
                    <br>
                    <label>{% trans "Date:" %}</label>
                    {{chosen_date}}
                    <br>
            <input class="form-control btn btn-primary" type="submit" name="submit">
            </div>
            </form>
        </div>
        <div class="card card-body">
            <table id="table_id" class="table display text-center">
                <thead>
                <tr>
                    <th>{% trans "Order ID" %}</th>
                    <th>{% trans "Customer" %}</th>
                    <th>{% trans "Date" %}</th>
                    <th>{% trans "Vehicle" %}</th>
                    <th>{% trans "Total Piece" %}</th>
                    <th>{% trans "Total Panne" %}</th>
                    <th>{% trans "HT" %}</th>
                    <th>{% trans "TVA" %}</th>
                    <th>{% trans "Discount" %}</th>
                    <th>{% trans "TTC" %}</th>
                    <th>{% trans "Debt" %}</th>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                {% for order in sellorders %}

                <tr>
                    <td>{{order.id}}</td>
                    <td>{{order.customer}}</td>
                    <td>{{order.order_date}}</td>
                    <td>{{order.vehicle}}</td>
                    <td>{{order.get_total_cost}} {% trans "DZD" %}</td>
                    <td>{{order.get_total_panne}} {% trans "DZD" %}</td>
                    <td>{{order.get_total_item_panne}} {% trans "DZD" %}</td>
                    <td>{{order.get_tva}} {% trans "DZD" %}</td>
                    <td>{{order.discount_amount}} {% trans "DZD" %}</td>
                    <td>{{order.get_ttc}} {% trans "DZD" %}</td>
                    <td>{{order.debt}} {% trans "DZD" %}</td>


                    <td>
                        {% if order.factured %}
                        {% else %}
                             <a class="btn btn-primary " href="{% url 'sellorder:sellorder_facture' order.id %}">{% trans "Facture" %}</a>
                        {% endif %}
                    </td>
                    <td>
                        {% if order.confirmed %}
                             <a class="btn btn-info " href="{% url 'sellorder:update_order' order.id %}">{% trans "Update" %}</a>
                        {% else %}
                             <a class="btn btn-success " href="{% url 'sellorder:confirm_order' order.id %}">{% trans "Confirm" %}</a>
                        {% endif %}
                    </td>
                    <td>
                        {% if order.debt > 0 and order.confirmed %}
                            <a class="btn btn-primary " href="{% url 'payments:create_customer_payment' order.id %}">{% trans "PayDebt" %}</a>
                        {% else %}
                        {% if not order.confirmed %}
                            <a class="btn btn-primary " href="{% url 'sellorder:update_order_performa' order.id %}">{% trans "Update" %}</a>
                        {% endif %}
                        {% endif %}
                    </td>

                    <td>
                           <a class="btn btn-warning " href="{% url 'sellorder:sellorder_details' order.id %}">{% trans "Details" %}</a>
                    </td>
                    <td>
                           <a class="btn btn-danger " href="{% url 'sellorder:sellorder_delete' order.id %}">{% trans "Delete" %}</a>
                    </td>
                </tr>

                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>


{% endblock %}
{% block jsscript %}
<!-- Date Picker-->
<script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />

<!-- custom javascript -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.jquery.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.min.css"/>
<!-- Data Table  -->
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.css">

<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.js"></script>
<!-- Date Picker-->
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>

<script type='text/javascript'>
    //Data Table init
    $(document).ready( function () {
    $('#table_id').DataTable();
    $('#table_customer').DataTable();
} );

// Date Picker
$('input[name="date"]').daterangepicker();

</script>
{% endblock %}